- Sources/MySQLNIO/MySQLConnection.swift
- Sources/MySQLNIO/MySQLConnectionHandler.swift
- Sources/MySQLNIO/Protocol/MySQLProtocol+CapabilityFlags.swift
Fixes an issue where connect would hang infinitely if `tlsConfiguration` was set to `nil`. This was because the `CLIENT_SSL` capability was accidentally enabled by default last release and that causes MySQL to always setup TLS. 
Some additional trace logs were added as well to help future debugging.
> fix hanging issue when tls is declined

- Sources/MySQLNIO/Protocol/MySQLProtocol+COM_STMT_EXECUTE.swift
- Tests/MySQLNIOTests/NIOMySQLTests.swift
Add support for encoding dynamically sized values longer than 251 bytes (fixes #23).
> Implement length encoding

- Sources/MySQLNIO/MySQLData.swift
- Tests/MySQLNIOTests/NIOMySQLTests.swift
- Adds support for converting `Foundation.Date` to/from MySQL `DATE` column type (#25). 
- `Swift.Bool` now serializes as `TINYINT` by default (#25).
> Date and Bool fixes

- Sources/MySQLNIO/MySQLData.swift
Adds support for `.tinyBlob`, `.mediumBlob`, and `.longBlob` to `MySQLData.string` (#26, fixes https://github.com/vapor/mysql-kit/issues/275).
> Decode string from tiny, medium and long blob

- Sources/MySQLNIO/Protocol/MySQLProtocol+BinaryResultSetRow.swift
Fixes an issue causing MySQLRow to retain large amounts of memory (#28). 
> Note: Adds an explicit copy to MySQLRow value byte buffer slices allowing wire protocol buffers to be released from memory.
> Copy row byte buffer slices

- Sources/MySQLNIO/MySQLConnection.swift
- Fix a user-unsolvable crash triggered by any failure whatsoever during the wire protocol handshake.
- Propagate loggers a bit better.
See Git commit log for a detailed explanation of the problem and its solution.
No API changes or additions.
> MySQL driver no longer crashes on auth failures

- .github/workflows/test.yml
- Sources/MySQLNIO/MySQLConnectionHandler.swift
- Sources/MySQLNIO/MySQLDatabase.swift
- Sources/MySQLNIO/MySQLQueryCommand.swift
- Tests/MySQLNIOTests/NIOMySQLTests.swift
- Tests/MySQLNIOTests/Utilities.swift
- docker-compose.yml
Fixes a bug causing query statements to not be cleaned up (closed) if an error was thrown in the `onRow` callback (#32, fixes https://github.com/vapor/mysql-nio/issues/30).
> Fix statement close on error

- Sources/MySQLNIO/MySQLConnectionHandler.swift
- Sources/MySQLNIO/MySQLQueryCommand.swift
- Tests/MySQLNIOTests/MySQLNIOTests.swift
- Tests/MySQLNIOTests/NIOMySQLTests.swift
- docker-compose.yml
Fixes an issue causing prepared statements to not close if an error happened during parameter binding (#34). 
> notes: MySQL NIO will now assert that statements have been closed before the query handler deinitializes.
> Fix statement close during binding

- Sources/MySQLNIO/MySQLData.swift
- Sources/MySQLNIO/MySQLDataConvertible.swift
- Tests/MySQLNIOTests/MySQLNIOTests.swift
Improves `Foundation.Decimal` support on `MySQLData` (#35).
> Fix decimal handling for MySQLData

- Sources/MySQLNIO/MySQLConnectionHandler.swift
- docker-compose.yml
Adds a check to ensure the server version is supported (#41, fixes #39). 
Unsupported MySQL server versions will now log an error during handshake.
> Add server version check

- Sources/MySQLNIO/MySQLData.swift
- Sources/MySQLNIO/MySQLTime.swift
- Tests/MySQLNIOTests/MySQLNIOTests.swift
Adds support for  8 and 12 byte (time only) `MYSQL_TIME` formats (#50, fixes #49). 
⚠️ Breaking change: Makes `MySQLTime` stored properties and `date` optional. Previously these methods could crash when used with a time-only value.
> MYSQL_TIME improvements

- .github/contributing.md
- README.md
- Sources/MySQLNIO/MySQLConnection.swift
- Sources/MySQLNIO/MySQLConnectionHandler.swift
- Sources/MySQLNIO/MySQLData.swift
Adds docs and implements missing functionality from PostgresNIO (#52).
- Adds `README` docs.
- Adds `contributing.md` docs
- Adds missing `MySQLData` fixed-width integer properties (`int8`, `int16`, `uint32`, etc).
- Adds `serverHostname` parameter to `MySQLConnection.connect`.
> Docs + missing functionality

- Sources/MySQLNIO/MySQLData.swift
- Sources/MySQLNIO/MySQLTime.swift
- Tests/MySQLNIOTests/MySQLNIOTests.swift
Fixes an issue causing `MYSQL_TIME` to use an incorrect data type when sending time or date only values (#54).
> Fix MYSQL_TIME data type

- Sources/MySQLNIO/MySQLConnectionHandler.swift
- Sources/MySQLNIO/MySQLError.swift
- Sources/MySQLNIO/MySQLTime.swift
- Sources/MySQLNIO/Packet/MySQLPacket.swift
- Sources/MySQLNIO/Utilities/CryptoUtils.swift
- Tests/MySQLNIOTests/MySQLNIOTests.swift
- Tests/MySQLNIOTests/Utilities.swift
Fixes the following failure modes:
- In tests, certain errors would crash instead of failing
- The `xor(_:_:)` utility did not correctly apply the operation to the entire buffer.
- Most protocol errors now throw a much more specific error.
- Trace logging is now more verbose during authentication.
- The `AuthSwitchRequest` packet (tagged with `0xfe` during the authentication phase, incorrectly treated as EOF before) is now correctly handled; this permits both the use of arbitrary auth plugins and the use of the "fast auth" mechanism.
- The `caching_sha2_password` handling would previously incorrectly treat the trailing `NUL` as part of the auth data.
- The `fast_auth_success` (`0x1 0x3`) packet during authentication is now correctly handled.
- When the `caching_sha2_password` plugin fails …
> Major fixes to authentication support

- .github/workflows/test.yml
- Sources/MySQLNIO/MySQLConnectionHandler.swift
- Sources/MySQLNIO/Protocol/MySQLProtocol+COM_STMT_EXECUTE.swift
- Sources/MySQLNIO/Protocol/MySQLProtocol+CapabilityFlags.swift
- Sources/MySQLNIO/Protocol/MySQLProtocol+HandshakeResponse41.swift
- Sources/MySQLNIO/Utilities/NIOUtils.swift
- Tests/MySQLNIOTests/Utilities.swift
The following changes have been made:
- When using the `mysql_native_password` auth plugin (or when authenticating with MySQL 5.7 in general), an empty password is now correctly treated as specifying no password at all. Fixes https://github.com/vapor/fluent-mysql-driver/issues/195.
- The `.CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA` capability, which improves and simplifies auth handling in some common cases, is now correctly supported and reported as such.
- The unit tests now support the `MYSQL_USERNAME`, `MYSQL_PASSWORD`, `MYSQL_DATABASE`, and `MYSQL_PORT` env vars.
- Small code cleanups.
> Fix auth using empty password with MySQL 5.7

- Sources/MySQLNIO/Protocol/MySQLProtocol+TextResultSetRow.swift
- Tests/MySQLNIOTests/MySQLNIOTests.swift
When `TextResultSetRow` encountered a null column, it did not increment the buffer index, and so it would repeatedly read `NULL` into every remaining column. This patch fixes the issue and adds regression tests (#57).
> Fix handling of null columns in TextResultSetRow

- Sources/MySQLNIO/Protocol/MySQLProtocol+HandshakeV10.swift
- Sources/MySQLNIO/Utilities/NIOUtils.swift
- Replace the `readNullTerminatedString()` implementation with the much more efficient version used by PostgresNIO.
- Made `writeNullTerminatedString()`, `writeLengthEncodedInteger()`, and `writeLengthEncodedSlice()` return the number of bytes written, to match `ByteBuffer` method conventions.
- Simplified `[read|write]LengthEncodedInteger()`, might be slightly faster but probably not enough to notice.
- Remove a couple of unused utility methods altogether.
> Clean up the ByteBuffer utility methods

- Package.swift
> Widen our pin on Crypto versions: `"1.0.0" ..< "3.0.0"`

- Sources/MySQLNIO/MySQLConnection.swift
- Sources/MySQLNIO/MySQLError.swift
- Sources/MySQLNIO/MySQLQueryCommand.swift
- Sources/MySQLNIO/MySQLSimpleQueryCommand.swift
- Tests/MySQLNIOTests/MySQLNIOTests.swift
- "Connection closed" errors are now correctly reported when trying to issue queries on closed connections, instead of throwing various NIO errors.
- Query syntax errors are now explicitly reported.
- Unique constraint violation errors are now more consistently reported.
`semver-minor` due to adding a new case on `MySQLError`.
> Improve error handling

- .github/dependabot.yml
- .github/workflows/test.yml
- Sources/MySQLNIO/MySQLQueryCommand.swift
- Sources/MySQLNIO/MySQLSimpleQueryCommand.swift
This logging is handled in MySQLKit and should not be present at the MySQLNIO layer.
> Avoid double-logging queries
